=== mzubok/issuetracker_sergei_doroshenko/src/main/resources/xml/issue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3schools.com"
	xmlns="http://www.w3schools.com"
	elementFormDefault="qualified">
	<xs:element name="issues">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="issue" type="issuetype" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="issuetype">
		<xs:sequence>
			<xs:element name="createdate" type="xs:date"/>
			<xs:element name="createby" type="xs:string"/>
			<xs:element name="modifydate" type="xs:date"/>
			<xs:element name="modifyby" type="xs:string"/>
			<xs:element name="summary" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="status" type="xs:long"/>
			<xs:element name="resolution" type="xs:long" minOccurs="0"/>
			<xs:element name="type" type="xs:long"/>
			<xs:element name="priority" type="xs:long"/>
			<xs:element name="project" type="xs:long"/>
			<xs:element name="assignee" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:long" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== mzubok/issuetracker_sergei_doroshenko/src/main/resources/xml/issues.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:issues xmlns:p="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../../../../target/classes/xml/issue.xsd ">
  <p:issue id="1" name="First">
    <p:createdate>2013-12-28</p:createdate>
    <p:createby>ajolie@gmail.com</p:createby>
    <p:modifydate>2013-12-29</p:modifydate>
    <p:modifyby>ajolie@gmail.com</p:modifyby>
    <p:summary>This first bag</p:summary>
    <p:description>This is the first test bag that has been created.</p:description>
    <p:status>1</p:status>
    <p:type>2</p:type>
    <p:priority>4</p:priority>
    <p:project>1</p:project>
    <p:assignee>jlo@gmail.com</p:assignee>
  </p:issue>
  <p:issue id="2" name="Second">
    <p:createdate>2013-12-21</p:createdate>
    <p:createby>ajolie@gmail.com</p:createby>
    <p:modifydate>2013-12-22</p:modifydate>
    <p:modifyby>ajolie@gmail.com</p:modifyby>
    <p:summary>This second bag</p:summary>
    <p:description>This is the second test bag that has been created.</p:description>
    <p:status>1</p:status>
    <p:type>2</p:type>
    <p:priority>4</p:priority>
    <p:project>1</p:project>
    <p:assignee>jlo@gmail.com</p:assignee>
  </p:issue>
  <p:issue id="3" name="Third">
    <p:createdate>2013-12-15</p:createdate>
    <p:createby>ajolie@gmail.com</p:createby>
    <p:modifydate>2013-12-22</p:modifydate>
    <p:modifyby>jlo@gmail.com</p:modifyby>
    <p:summary>This third bag</p:summary>
    <p:description>This is the third test bag that has been created.</p:description>
    <p:status>1</p:status>
    <p:type>1</p:type>
    <p:priority>3</p:priority>
    <p:project>2</p:project>
    <p:assignee>ajolie@gmail.com</p:assignee>
  </p:issue>
</p:issues>
