=== mzubok/issuetracker_sergei_doroshenko/src/main/resources/xml/user.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3schools.com"
	xmlns="http://www.w3schools.com"
	elementFormDefault="qualified">
	<xs:element name="users">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="user" type="usertype" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="usertype">
		<xs:sequence>
			<xs:element name="id" type="xs:long"/>
			<xs:element name="firstname" type="xs:string"/>
			<xs:element name="lastname" type="xs:string"/>
			<xs:element name="email" type="xs:string"/>
			<xs:element name="roleid" type="xs:long"/>
			<xs:element name="password" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== mzubok/issuetracker_sergei_doroshenko/src/main/resources/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:users xmlns:p="http://www.w3schools.com" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.w3schools.com ../../../../target/classes/xml/user.xsd ">
  <p:user>
    <p:id>1</p:id>
    <p:firstname>Sergei</p:firstname>
    <p:lastname>Doroshenko</p:lastname>
    <p:email>6823298@gmail.com</p:email>
    <p:roleid>1</p:roleid>
    <p:password>11111</p:password>
  </p:user>
  <p:user>
    <p:id>2</p:id>
    <p:firstname>Angelina</p:firstname>
    <p:lastname>Jolie</p:lastname>
    <p:email>ajolie@gmail.com</p:email>
    <p:roleid>2</p:roleid>
    <p:password>11111</p:password>
  </p:user>
  <p:user>
    <p:id>3</p:id>
    <p:firstname>Jennifer</p:firstname>
    <p:lastname>Lopez</p:lastname>
    <p:email>jlo@gmail.com</p:email>
    <p:roleid>2</p:roleid>
    <p:password>11111</p:password>
  </p:user>
</p:users>
